version: '2'
services:
  web:
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0
      - 'RUN=flask run --host=0.0.0.0 --port=80'
      - VIRTUAL_HOST=a.domain.org
      - LETSENCRYPT_HOST=a.domain.org
      - LETSENCRYPT_EMAIL=user@a.domain.org
      - LETSENCRYPT_TEST=false
      - IGDB_API_KEY=a_key
    command: flask run --host=0.0.0.0 --port=80
    container_name: lol9k1
    networks:
      - proxy
networks:
  proxy:
    external:
      name: nginx_proxy